### ISSUE TITLE
duration always 0 in MAF.mediaplayer#onTimeIndexChanged event payload

### ISSUE THREAD

**Issue by 1024kilobyte** [Metrological/maf3-sdk#10]
Since I upgraded my environment to the current version of the sdk (3.7.4) the value of event.payload.duration is always 0. The value of timeIndex seems to be correct. I used this to calculate the progress in percent, which is now broken.

**Comment by albertd** [comment]
Resolved in 3.7.5 (https://github.com/Metrological/maf3-sdk/commit/f9e21164e8bb94a69c151562139a492c062e602f)

**Comment by 1024kilobyte** [comment]
I just double checked with the current version and duration is still reported to be 0.

**Comment by albertd** [comment]
Resolved in 3.7.6 (https://github.com/Metrological/maf3-sdk/commit/a87743f116fd7f36454aa4b7774ca75a576d9601)
